### ISSUE TITLE
Need to free up space on PyPI

### ISSUE THREAD

**Issue by alugowski** [GraphBLAS/python-suitesparse-graphblas#133]
The latest build succeeded, but PyPI only accepted some of the files because we're hitting our 20GB quota:

See https://github.com/GraphBLAS/python-suitesparse-graphblas/actions/runs/11390632136/job/31701653980
```
 Uploading suitesparse_graphblas-9.3.1.0-cp312-cp312-macosx_14_0_arm64.whl
INFO     Response from https://upload.pypi.org/legacy/:                         
         400 Project size too large. Limit for project 'suitesparse-graphblas'  
         total size is 20 GB. See https://pypi.org/help/#project-size-limit     
INFO     <html>                                                                 
          <head>                                                                
           <title>400 Project size too large. Limit for project                 
         'suitesparse-graphblas' total size is 20 GB. See                       
         https://pypi.org/help/#project-size-limit</title>                      
          </head>                                                               
          <body>                                                                
           <h1>400 Project size too large. Limit for project                    
         'suitesparse-graphblas' total size is 20 GB. See                       
         https://pypi.org/help/#project-size-limit</h1>                         
           The server could not comply with the request since it is either      
         malformed or otherwise incorrect.<br/><br/>                            
         Project size too large. Limit for project                              
         &#x27;suitesparse-graphblas&#x27; total size is 20 GB. See             
         https://pypi.org/help/#project-size-limit            
```

We do have a lot of old versions. Each recent version is over a gig. The recent alphas that we used for testing are a great candidate for delete, and going back we could keep only the latest point release to free up space.

Note that despite what the badge says, only some 9.3.1 files are up. Once some space is freed up simply rerun just the upload step in the link above (shouldn't have to rebuild all the wheels).

Can someone with PyPI access free up some space and press that re-run button?

**Comment by eriknw** [comment]
Done, and uploaded.

I deleted the alpha releases as you suggested.

What should the long term strategy for support be to stay within the space quota?

- We should keep _all_ source distributions, forever, except for pre-releases
- We should keep all wheels for a limited set of recent releases
  - Should this be based on version number? For example, support the latest `X` version (e.g., the latest `7`, `8`, and `9`, so we would have `8.2.1` and `7.4.4`, but not `8.0.2`.) or `X.Y` version?
- We should delete old wheels when needed (it's cheap to reupload to PyPI)
- When we delete wheels, should we keep `manylinux` wheels for longer?

Also, perhaps we could look into using [`Py_LIMITED_API`](https://docs.python.org/3/c-api/stable.html) to reduce the number of wheels.
