### ISSUE TITLE
Build a wheel, conda package and docker images.

### ISSUE THREAD

**Issue by michelp** [GraphBLAS/python-suitesparse-graphblas#2]

**Comment by MridulS** [comment]
Just wanted to bump this up. There seems to be only Linux wheels available on PyPI https://pypi.org/project/suitesparse-graphblas/#files right now, it would great to get Mac and windows wheels too so its easy to distribute packages like [graphblas-algorithms](https://github.com/python-graphblas/graphblas-algorithms).

**Comment by eriknw** [comment]
Thanks for the push @MridulS.  I definitely agree.  I've built Mac and Windows wheels manually in the past, so it can be done (but it's a pain to do by hand).  I need to learn to use cibuildwheel anyway.

Do you have a timeline in mind for this @MridulS?  The earlier the better, but I think it's a must have by early July.

**Comment by MridulS** [comment]
There is no hurry but yeah getting the wheels out would help with getting more people to play around with graphblas :)

**Comment by eriknw** [comment]
We now have wheels and conda packages for all major OSes and architectures.

Can we close this issue? How important/useful is it to build docker images?

**Comment by alugowski** [comment]
> We now have wheels and conda packages for all major OSes and architectures.

🎉

> Can we close this issue?

Perhaps close when the PyPI stable version points at the wheels?

> How important/useful is it to build docker images?

Maybe @michelp can clarify more, but I think working wheels fill all niches that a docker image would.

**Comment by alugowski** [comment]
We have working wheels on PyPI, so this appears complete.
