### ISSUE TITLE
Fast creation and access for matrices and vectors

### ISSUE THREAD

**Issue by steffen-sch** [GraphBLAS/python-suitesparse-graphblas#34]
Hello,

I've done some experiments on the performance of sparse matrix vector multiplication in Python with pygraphblas and grblas.
The speed of the multiplication is way faster than the SciPy.sparse implementation. Unfortunately the creation of matrices and vectors and the transfer to and from SciPy.sparse and Numpy objects is very slow. The IO operations eat the gained time by the fast multiplication. 

Now my questions: 
Is it much work to implement wrappers for functions like GrB_Vector_build to speed up the IO operations?
Is there much work for memory management if you implement these IO wrappers?

Thanks for the nice package and your time

**Comment by eriknw** [comment]
Cool, thanks for giving GraphBLAS a try!  I'm curious to see the performance comparison.

In `grblas`, I would recommend using `Matrix.from_values` (which calls `GrB_Matrix_build` or `GxB_Matrix_build_scalar`) or methods such as `Matrix.ss.import_csr`, `Matrix.ss.import_csc`, etc.  These accept NumPy arrays, and the "import" methods can even "zero-copy" into SuiteSparse:GraphBLAS if you opt-in to giving GraphBLAS ownership of your arrays.

Here's a list of import functions (also available as e.g. `pack_csr` for existing matrices):
- `import_csr`
- `import_csc`
- `import_hypercsr`
- `import_hypercsc`
- `import_bitmapr`
- `import_bitmapc`
- `import_fullr`
- `import_fullc`
- `import_coo`
- `import_coor`
- `import_cooc`
- `import_any`

Ideally, we'd love to move this functionality to `python-suitesparse-graphblas`, but nobody has had the bandwidth to do this.

**Comment by eriknw** [comment]
Also, to go back to Python objects, see `A.to_values` and `A.ss.export` methods in `grblas`.  As with the "import" methods, `.ss.export` is able to "zero-copy" to numpy arrays.

**Comment by eriknw** [comment]
Hi @steffen-sch have you been able to make any more progress?  Do you have any more questions?  Have any benchmark comparisons to share ;) ?

I believe I addressed the issue you raised, so I am closing.  Feel free to re-open this issue if I am mistaken, or feel free to add any comments to the closed issue.

**Comment by steffen-sch** [comment]
Hi @ eriknw, thank you for your suggestions.  I have tested them and also done some benchmarks. This pretty much solved my problem. Unfortunately the pandemic stopped my work in the last two weeks.  I will post my benchmark results soon.
