### ISSUE TITLE
test_matrix_binfile_read_write fail on various architectures

### ISSUE THREAD

**Issue by ViviCoder** [GraphBLAS/python-suitesparse-graphblas#56]
On armhf, ppc64el, ppc64, and riscv64 Debian machines, one gets the following test failure:
```
============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-7.1.2, pluggy-1.0.0+repack
rootdir: /<<PKGBUILDDIR>>, configfile: setup.cfg
collected 7 items

suitesparse_graphblas/tests/test_doctest.py .                            [ 14%]
suitesparse_graphblas/tests/test_exceptions.py .                         [ 28%]
suitesparse_graphblas/tests/test_io.py ..F                               [ 71%]
suitesparse_graphblas/tests/test_package.py .                            [ 85%]
suitesparse_graphblas/tests/test_scalar.py .                             [100%]

=================================== FAILURES ===================================
________________________ test_matrix_binfile_read_write ________________________

tmp_path = PosixPath('/tmp/pytest-of-buildd/pytest-0/test_matrix_binfile_read_write0')

    def test_matrix_binfile_read_write(tmp_path):
        for opener in (Path.open, gzip.open, bz2.open, lzma.open):
            for format in (lib.GxB_BY_ROW, lib.GxB_BY_COL):
                for T in grb_types:
                    for sparsity in (lib.GxB_HYPERSPARSE, lib.GxB_SPARSE, lib.GxB_BITMAP, lib.GxB_FULL):
    
                        A = matrix.new(T, 2, 2)
    
                        if T is not lib.GxB_FULL:
                            for args in zip(*_test_elements(T)):
                                f = _element_setters[T]
                                check_status(A, f(A[0], *args))
                        else:
                            Tone = _test_elements(T)[0][0]
                            check_status(
                                A[0],
                                lib.GrB_assign(
                                    A,
                                    NULL,
                                    NULL,
                                    Tone,
                                    lib.GrB_ALL,
                                    0,
                                    lib.GrB_ALL,
                                    0,
                                    NULL,
                                ),
                            )
                        matrix.set_sparsity_control(A, sparsity)
                        matrix.set_format(A, format)
    
                        binfilef = tmp_path / "binfilewrite_test.binfile"
                        binary.binwrite(A, binfilef, opener=opener)
                        B = binary.binread(binfilef, opener=opener)
    
                        assert matrix.type(A) == matrix.type(B)
                        assert matrix.nrows(A) == matrix.nrows(B)
                        assert matrix.ncols(A) == matrix.ncols(B)
>                       assert matrix.hyper_switch(A) == matrix.hyper_switch(B)
E                       AssertionError: assert 0.0625 == 0.0
E                        +  where 0.0625 = <function hyper_switch at 0x7fffa61975b0>(<cdata 'struct GB_Matrix_opaque * *' 0x1000e6b6660>)
E                        +    where <function hyper_switch at 0x7fffa61975b0> = matrix.hyper_switch
E                        +  and   0.0 = <function hyper_switch at 0x7fffa61975b0>(<cdata 'struct GB_Matrix_opaque * *' 0x1000e7118d0>)
E                        +    where <function hyper_switch at 0x7fffa61975b0> = matrix.hyper_switch

suitesparse_graphblas/tests/test_io.py:176: AssertionError
=========================== short test summary info ============================
FAILED suitesparse_graphblas/tests/test_io.py::test_matrix_binfile_read_write
========================= 1 failed, 6 passed in 0.24s ==========================
```

**Comment by ViviCoder** [comment]
I am using version 7.3.2.0, but the bug was already present with version 7.2.0.0.

Tests are run after building the package from source.
Here is a full Debian build log: https://buildd.debian.org/status/fetch.php?pkg=python-suitesparse-graphblas&arch=ppc64&ver=7.3.2.0-1&stamp=1668629267&raw=0.

**Comment by eriknw** [comment]
Thanks @ViviCoder for the info and for helping with the Debian builds.

We have recently tried adding support for other architectures, but we have a hard time testing them, so this is actually very helpful. Specifically, cffi has issues when wrapping variadic functions on different architectures. We added tried workarounds for arm64 and ppc64le in #50 and #51.

We may need to detect more platforms here:
https://github.com/GraphBLAS/python-suitesparse-graphblas/blob/95d5fdc15dc014696c36f3317ceb216fbaf04acf/suitesparse_graphblas/__init__.py#L9-L36

@ViviCoder, can you figure out what `platform.machine()` returns in Python for the failing builds? Can you apply patches to update the logic of which `vararg` function to use? Once we figure out which platforms need which `vararg` function, we'll be happy to update `python-suitesparse-graphblas` and cut a new release.

**Comment by ViviCoder** [comment]
Here are the values for `platform.machine()`:
- armhf (and armel, which will probably fail once https://github.com/DrTimothyAldenDavis/GraphBLAS/issues/178 is solved): armv7l,
- ppc64: ppc64,
- riscv64: riscv64.

I will try to add these values to those you already have and see if tests succeed.

**Comment by ViviCoder** [comment]
Here is my understanding of the problem for armv7l: as for arm64, variadic arguments must be send to the stack, but contrary to arm64, casting it to an argument of type `char *` does not work for `double` arguments, because `char *` is only 4 bytes.

**Comment by eriknw** [comment]
Thanks again for your work on this @ViviCoder and the latest updates.

As a potential solution, should we try using `int8_t *` instead of `char *`?

**Comment by ViviCoder** [comment]
The problem is not that `char` is too small, but that `char *` is (as a pointer, not as an array).
As far as I know, `int8_t *` has the same size as `char *`.
What we could try is to cast `double` variadic arguments into two separate `char *` arguments so that they are next to each other in the stack.

**Comment by ViviCoder** [comment]
I do not know if this can be of any help, but I noticed that the failure for armhf (and armel, I assume) is slightly different: instead of `AssertionError: assert 0.0625 == 0.0`, one gets `AssertionError: assert 0.0625 == -inf`.

**Comment by DrTimothyAldenDavis** [comment]
This problem would go away if GxB_get/set didn't use va_arg, right?

I could instead convert methods like GxB_set/get to use type-specific methods, like a new GxB_Global_Option_set_INT64 (and related types).  The user code would remain unchanged.  I could even keep the va_arg-based methods but allow them to be disabled with an #ifndef NO_VA_ARG_PLEASE ... or something.

This would be a modest change to the GxB_get/set since the user's code would typically not change.  I could even change GxB_Global_Option_set into a macro that use the _Generic keyword.

This would require a bump to GraphBLAS v8, however, since the old va_arg methods would be removed.

**Comment by ViviCoder** [comment]
Yes, I guess.

It could also be worth reporting the issue to the maintainers of cffi.

**Comment by DrTimothyAldenDavis** [comment]
This will be pretty quick to add.  See my draft v7.4.0 with the new type-specific GxB_Global_Option_set and get methods, with no va_arg.  The tests pass so far, as well:

https://github.com/DrTimothyAldenDavis/GraphBLAS/tree/v740

You can see from the first commit what differs from v7.3.3, particular the new functions in the GraphBLAS.h file:

https://github.com/DrTimothyAldenDavis/GraphBLAS/commit/989b252b85d8b473c0fc383654cf3d949e5bc89d

I still have to write the type-specific methods for the GxB_Matrix_Option_set/get, GxB_Vector_Option_set/get, and GxB_Desc_set/get, but those should be quick.  I haven't added these to the user guide yet.

You don't need these in a _Generic macro, right?  It would be easier to skip that, and leave my GxB_set and GxB_get macros the same.

I'll keep the existing methods with va_arg.  The Python cffi can just avoid calling any of those methods.

**Comment by eriknw** [comment]
Thanks @DrTimothyAldenDavis! Correct, we don't need (and can't directly use) the macros. I like your plan.

Our automated tooling picked up the additions just fine. See: #58

**Comment by DrTimothyAldenDavis** [comment]
See the new v7.4.0.beta1: https://github.com/DrTimothyAldenDavis/GraphBLAS/releases/tag/v7.4.0.beta1 .  I now have va_arg-free methods for all GxB set/get functions.  Test coverage is 100% so the beta1 is pretty stable.

I didn't add these to the user guide (see the Doc/Changelog), because they will only be needed until the v2.1 C API Spec comes out, and because most applications will be able to use the existing _Generic GxB_set / GxB_get.  I will keep them "forever"; I'll just declare these new va_arg-free get/set methods as "historical" when the GrB_get/set methods are available.

**Comment by eriknw** [comment]
Thanks @DrTimothyAldenDavis! Avoiding variadic is the best solution for this IMHO.

7.4.0.beta1 passes our normal tests and is able to do our normal builds:
- https://github.com/GraphBLAS/python-suitesparse-graphblas/pull/58
- https://github.com/conda-forge/graphblas-feedstock/pull/58

I'll update `python-graphblas` once SuiteSparse:GraphBLAS 7.4.0 is released (we don't have a good workflow for beta and RC releases yet).

**Comment by DrTimothyAldenDavis** [comment]
I just posted the stable v7.4.0. It passes all my tests
-- 
Sent from Gmail Mobile

**Comment by eriknw** [comment]
@ViviCoder, `python-suitesparse-graphblas` version 7.4.0.0 and `python-graphblas` version 2022.12.0 have been released. These use the non-variadic get and set functions that Tim added in SuiteSparse:GraphBLAS 7.4.0, so I expect them to work on more architectures.

Care to give them a try when you have the time? Thanks again for working on this!

**Comment by ViviCoder** [comment]
I confirm that `python-suitesparse-graphblas` 7.4.0.0 works on all architectures officially supported by Debian.

It means that #48 is also fixed.

**Comment by eriknw** [comment]
Hooray :tada:

Closing :)
