### ISSUE TITLE
Document how to install `python-suitesparse-graphblas` with pre-installed SuiteSparse:GraphBLAS

### ISSUE THREAD

**Issue by eriknw** [GraphBLAS/python-suitesparse-graphblas#79]
Some users may prefer to install SuiteSparse:GraphBLAS on their own, so we should document how to install `python-suitesparse-graphblas` from the source distribution (sdist) from PyPI or the developer version from the repository.

**Comment by alugowski** [comment]
I believe this was actually impossible? The build would look in `sys.prefix` on unix and `C:/GraphBLAS` on Windows. I made a PR to make this selectable with an environment variable, the same variable you have to set when using FindGraphBLAS with CMake.
