### ISSUE TITLE
Wheel build for 8.0.0 on macos x86_64 is failing tests

### ISSUE THREAD

**Issue by eriknw** [GraphBLAS/python-suitesparse-graphblas#89]
See: https://github.com/GraphBLAS/python-suitesparse-graphblas/actions/runs/5035542365/jobs/9031130433

Raw log attached for posterity: [macos_x86_64_log.txt](https://github.com/GraphBLAS/python-suitesparse-graphblas/files/11526377/macos_x86_64_log.txt)

Looks like something bad is happening in `test_matrix_binfile_read_write`.

**Comment by eriknw** [comment]
I'm not sure if there is anything useful here, but I dumped the JIT config for the failing wheel build: https://github.com/GraphBLAS/python-suitesparse-graphblas/actions/runs/5161271671/jobs/929812306
```
===================================
  Printing default JIT configurations
  -----------------------------------
  JIT_C_CONTROL on
  JIT_USE_CMAKE False
  JIT_C_COMPILER_NAME /Applications/Xcode_14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
  JIT_C_COMPILER_FLAGS -arch x86_64 -O3 -DNDEBUG -Xclang -fopenmp -I/usr/local/opt/libomp/include  -fPIC  -arch x86_64  -isysroot /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk 
  JIT_C_LINKER_FLAGS -L/usr/local/opt/libomp/lib -dynamiclib 
  JIT_C_LIBRARIES  -lm -ldl -lomp
  JIT_C_CMAKE_LIBS m;dl;omp
  JIT_C_PREFACE 
  JIT_ERROR_LOG 
  JIT_CACHE_PATH /Users/runner/.SuiteSparse/GrB8.0.1
  ===================================
```

**Comment by alugowski** [comment]
Anecdotally I noticed that, at least for C++, builds on macOS seem to be a lot less tolerant of things like out-of-bounds memory accesses. Even reads. Usually on Linux and Windows you have to write to an entirely different page to trigger a segfault, it seems like surprisingly often a single byte out of range is enough to crash on macOS.

So maybe this is an upstream bug in eWiseMult that is just being caught on this platform. The JIT is new code, after all.
